### ISSUE TITLE
联合投稿不能折叠

### ISSUE THREAD

**Issue by miaonai** [Taosky/BiliMini#10]
![image](https://github.com/Taosky/BiliMini/assets/67116517/4b8cef80-f665-49a8-a9d0-883a5147b3ca)
希望联合投稿能折叠起来，类似下面这样
![image](https://github.com/Taosky/BiliMini/assets/67116517/51355a50-933e-4cff-8afd-08dc3d9b70be)

**Comment by Taosky** [comment]
Firefox版本应该已经支持了。
