### ISSUE TITLE
“投稿”页面重开出现空白

### ISSUE THREAD

**Issue by miaonai** [Taosky/BiliMini#11]
一开始可以正常打开，选择“投稿”页面，关闭扩展页面再重新打开，“投稿”页面上就一片空白，下拉一段就会一直转圈，“投稿”页面上一片空白时选择其他页面又可以正常打开，再回到“投稿”页面就恢复正常了
如果一开始就选择其他页面关闭再打开，就是正常的

编辑：视乎是稍后再看功能的bug，添加一个视频稍后再看就解决了

Firefox Developer Edition118.0b9（64位）
BiliMini 2.3.6

![“投稿”页面](https://github.com/Taosky/BiliMini/assets/67116517/1930406e-381a-4bf7-9cc5-8bfdb92e4a56)

**Comment by Taosky** [comment]
清空稍后再看复现了，马上修。

**Comment by Taosky** [comment]
Firefox版本已更新修复。
