### ISSUE TITLE
时间样式不一致

### ISSUE THREAD

**Issue by miaonai** [Taosky/BiliMini#12]
X分钟前和X小时前和XX月XX日--显示一致
XX分钟前----突出框外一部分（也许XX小时前也会有）
昨天XX:XX---左边一行显示且突出框外一部分，右边两行显示
刚刚和X天前--------不靠右对齐

![“投稿”页面](https://github.com/Taosky/BiliMini/assets/67116517/c8f48563-48e1-4683-aa80-062d14c5da7c)
![image](https://github.com/Taosky/BiliMini/assets/67116517/cf313a62-2b83-4392-a41b-f8263f2084c5) ![image](https://github.com/Taosky/BiliMini/assets/67116517/79917477-3a03-4115-91bd-0068768b45cf)

第一个是竖屏视频让旁边留下空白区域

![image](https://github.com/Taosky/BiliMini/assets/67116517/4a386430-6238-4e31-82fa-a51659619223)

**Comment by Taosky** [comment]
样式不太会搞，下个版本试着改改吧。
竖屏视频这个有点神奇，理论上两列是单独的...
