### ISSUE TITLE
Firefox最新版历史页面左键点击视频会打开两个窗口。

### ISSUE THREAD

**Issue by lisansas** [Taosky/BiliMini#13]
RT。

但中键点击就只有一个窗口。

还有，请问一下，之前的版本（九月之前），在任何界面都可以中键点击视频，但现在的版本在视频页面只能左键点击视频了

**Comment by Taosky** [comment]
是因为改成了Manifest V3，用了api打开链接，历史记录页面的a标签href忘记删除了。视频页面左键点击也是因为这个，之前是跟网页链接一样，现在是调用api打开，不支持鼠标中键。
