### ISSUE TITLE
火狐上2.3.8版会拦截网页版视频封面右上角的“添加到稍后再看”图标

### ISSUE THREAD

**Issue by TomoeMami** [Taosky/BiliMini#14]
![图片](https://github.com/Taosky/BiliMini/assets/16950305/5d199352-ef11-4fc2-84cc-c12a4ce3b7e9)

经反复比对发现是bilimini插件拦截了该图标

**Comment by Taosky** [comment]
确实是扩展拦截的，因为要修改请求头让扩展内的稍后再看能生效，目前没啥办法解决😓

**Comment by Taosky** [comment]
通过动态拦截修复了，关掉弹窗可能需要等几秒才正常。应用商店还没更新，需要再等等。
