### ISSUE TITLE
很棒的小工具 希望增加 弹窗快捷键 对于键盘档的福音 :)

### ISSUE THREAD

**Issue by c0001** [Taosky/BiliMini#3]

**Comment by Taosky** [comment]
已增加Alt+B / Option+B，Chrome和Edge版本在审核中，其实Chrome可以`chrome://extensions/shortcuts`里面直接设置。

**Comment by c0001** [comment]
感谢 实现这个feature， 其实主要是对于firefox来说（我主用firefox） 如果不主动申请快捷键扩展 是没有像chrome一样的默认toggler的。
