### ISSUE TITLE
追番完结或无追番会导致番剧 Tab 始终处于加载状态而无法正常使用 bilimini （卡死）

### ISSUE THREAD

**Issue by TaivasJumala** [Taosky/BiliMini#7]
之前能用的，现在只有小红点是正常的

卡在这：

![图片](https://user-images.githubusercontent.com/72904966/232308344-3aa31686-2da1-407d-a23d-067f1b2b7044.png)

并且无法切换 tab

有用 bili-evolved 不知道有没有影响

https://api.live.bilibili.com/relation/v1/feed/feed_list?page=1&pagesize=11

这个 api：

![图片](https://user-images.githubusercontent.com/72904966/232308310-9f347d20-e8cf-41ab-87f9-ba99b3c4434c.png)

不知道还要提供什么信息

**Comment by Taosky** [comment]
我这边没问题…版本是最新的吗？b站这个api短时间请求太多也会不行。

**Comment by TaivasJumala** [comment]
好像是不会自动更新：（

**Comment by Taosky** [comment]
> 好像是不会自动更新：（

额，是扩展没更新吗？
你发的那个api是直播页的，可以试下这个能不能有数据。
https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/dynamic_new?uid=&type_list=

**Comment by TaivasJumala** [comment]
拓展更新好了
不过你给的 api 是这样的：
![图片](https://user-images.githubusercontent.com/72904966/232311715-d3ea25c7-7b46-4007-8061-2404e6a79487.png)

**Comment by Taosky** [comment]
> 拓展更新好了
> 不过你给的 api 是这样的：
> ![图片](https://user-images.githubusercontent.com/72904966/232311715-d3ea25c7-7b46-4007-8061-2404e6a79487.png)

不好意思，少打了个8😅
https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/dynamic_new?uid=&type_list=8

**Comment by TaivasJumala** [comment]
有货了：
![图片](https://user-images.githubusercontent.com/72904966/232312214-e5e79a8f-30a2-4b33-a2cd-b7786eecce6c.png)


重装拓展第一次有东西，后面又像刚才那样了

**Comment by TaivasJumala** [comment]
![图片](https://user-images.githubusercontent.com/72904966/232312294-64cb9f8c-c4d3-4679-8eef-183c50b39d63.png)

**Comment by Taosky** [comment]
奇怪了，可以下个别的浏览器试试，看看是扩展的问题还是其他问题…

目前已经发现的一个问题是有时候会点不了视频链接，好像是B站API字段会变动。
这个问题不排除是API的原因。

这两天不太方便用电脑，之后会研究下。

**Comment by TaivasJumala** [comment]
大概能复现了

我平时用 Microsoft Edge 作为备用浏览器，啥插件都没装。

在 Edge 安装完 bilimini 之后，三个 tab 都能用，就是切换到番剧 tab 的时候会一直加载，导致无法切换到其他 tab。

**Comment by TaivasJumala** [comment]
我又又又懂了，因为我追的番都完结了，所以动态里的追番是空的。于是导致了此 bug，随便追了个番就正常了。

**Comment by Taosky** [comment]
> 我又又又懂了，因为我追的番都完结了，所以动态里的追番是空的。于是导致了此 bug，随便追了个番就正常了。

😥居然是这个问题，下次修一下。

**Comment by Taosky** [comment]
加了判断修复（2.2.5版本,Edge和Chrome审核比较慢）

**Comment by Taosky** [comment]
Edge 商店的版本审核通过了（真的好慢😓）。

**Comment by TaivasJumala** [comment]
我超，原来之前 Edge 上装的是 Chrome 商店上的吗
其实我是 Firefox 用户🐶

**Comment by Taosky** [comment]
> 我超，原来之前 Edge 上装的是 Chrome 商店上的吗 其实我是 Firefox 用户🐶

哈哈哈。
