### ISSUE TITLE
可否增加“添加到稍后再看”功能

### ISSUE THREAD

**Issue by lilyblessing** [Taosky/BiliMini#8]
增加“添加到稍后再看”功能，
如网页中动态悬浮小窗口中加一个小按钮快速添加到稍后再看

**Comment by Taosky** [comment]
挺好，不过感觉得先加一个稍后再看的tab页面，配合使用。

**Comment by lilyblessing** [comment]
似乎倒也不用，使用场景更多是不便、没空打开主站查看动态的时候快速扫一眼更新了哪些内容；

如果有需要看看的，就点一个添加稍后再看，然后等有空了再直接去稍后再看页面统一处理。

**Comment by Taosky** [comment]
Firefox版本已更新，Chrome/Edge审核比较慢，还要过一阵（而且有点Bug，最好等到2.3.7版本上架再用）。
